#!/bin/sh
##
# $Id: bootstrap,v 1.2 2003-07-02 17:48:13 achu Exp $
##

echo "running aclocal ... "
aclocal -I config
echo "running libtoolize ... "
libtoolize --automake --copy 
echo "running autoheader ... "
autoheader
echo "running automake ... "
automake --copy --add-missing 
echo "running autoconf ... "
autoconf
echo "now run ./configure to configure pdsh for your environment."
